/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205733;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BlackJackTest {
    @Test void BJdodistribute() {
        int correctNumCards = 2;
        BlackJack bl = new BlackJack();
        bl.distribute();
        assertEquals(correctNumCards,bl.numPlayerCard); // カードがプレイヤーに二枚配られているかのテスト
        
    }
}
